language:
  - go

sudo: true

go:
  - "1.13.x"

env:
  - GO111MODULE=on

before_install:
  chmod +x ./gin-docker/gin-docker/build.sh
  chmod +x ./link-gin-db/build.sh

script:
  - ./gin-docker/gin-docker/build.sh
  - ./link-gin-db/build.sh