version: '3'

services:
  redis:depends_on
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: on-failure
    command: redis-server --appendonly yes --bind 0.0.0.0

  mysql:
    image: mysql:5.7
    volumes:
      - "./db/mysql_data:/var/lib/mysql"
      - "./db/mysql_init:/docker-entrypoint-initdb.d/"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_docker_link
      MYSQL_USER: liangjf
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    restart: on-failure #no  always  on-failure  unless-stopped
    links:
      - mysql:mysql-server
      - redis:redis-server
    depends_on:
      - mysql
      - redis