version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      com.example.description: "docker link web"
      com.example.department: "laingjf"
    ports:
      - "7070:7070"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure #no  always  on-failure  unless-stopped
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend

  redis:
    image: "redis:alpine"
    networks:
      - backend
    restart: on-failure

  mysql:
    image: mysql:5.7
    volumes:
      - "./db:/var/lib/mysql"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_docker_link
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    networks:
      - backend

networks:
  backend: